### ISSUE TITLE
Does libtorch-java support CUDA?

### ISSUE THREAD

**Issue by FantasyJXF** [dreiss/java-demo#2]
The demo you provide is very efficient, and I have traced my model to inference with JAVA, my question is whether I could use CUDA to inference the model, since the java method of libtorch is far less than C++, and I didn't find the `to(kCUDA)` on https://pytorch.org/javadoc/.

Looking forward to your reply.

**Comment by dreiss** [comment]
We don't expose, `to(CUDA)` in the Java API, but it should be possible to run a CUDA model from libtorch+Java as long as all of the inputs/outputs are on CPU and the CUDA/CPU transfers are done within the TorchScript model.  Please try it out and let me know how it goes!

**Comment by FantasyJXF** [comment]
I suppose you meaned that I should trace the model with CUDA, so that if I load the traced CUDA model, the input tensor and forward process would automatically conducted within CUDA.

I tried this with PyTorch, it works.  libtorch-java to go.

**Comment by FantasyJXF** [comment]
I tihink I was wrong yesterday. If the model was in CUDA but input tensor in CPU, it would run into  TypeError.

```
Input type (CPUFloatType) and weight type (CUDAFloatType) should be the same (_convolution at /pytorch/aten/src/ATen/native/Convolution.cpp:449)
```

**Comment by dreiss** [comment]
Try following this pattern: https://gist.github.com/dreiss/76171f2d9241e78f805ef48c11f4bbdf

This way, all of the inter-device transfers happen in TorchScript, and Java should only see CPU tensors.

**Comment by FantasyJXF** [comment]
Many thanks.
The key is to wrapper the transfer process
```
def wrapper(inp):
    return fc_gpu(inp.cuda().detach()).cpu()
```

**Comment by fzwqq** [comment]
> Try following this pattern: https://gist.github.com/dreiss/76171f2d9241e78f805ef48c11f4bbdf
> 
> This way, all of the inter-device transfers happen in TorchScript, and Java should only see CPU tensors.

Execute me, how to set all the parameters without grad which load from checkpoint (pth). And does it the unique method use cuda in java?

**Comment by fzwqq** [comment]
In my test, it doesn’t use cuda at all.
